# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfridge', '0002_auto_20170529_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
